### ISSUE TITLE
Webpack + IE 11 not working with library

### ISSUE THREAD

**Issue by roma-formio** [Sphinxxxx/vanilla-picker#22]
Hi Andreas, maybe you can help me. I'm using vanilla-picker library on my application, but have troubles when trying to import Picker. All browsers work fine, only IE 11 throw error like 
```
SCRIPT1006: Expected ')'
```
 When trying to use the library with tag <script> all works fine.
Would be great if you can have a look into that.

**Comment by Sphinxxxx** [comment]
Hello!

Without seeing the output code, this is only guessing, but it may be because IE doesn't support some particular ES6 feature. [Possibly related SO question](https://stackoverflow.com/questions/44732066/script1006-expected).

Do you have Webpack transpile your code, for example using [Babel](https://medium.com/@jeffrey.allen.lewis/the-ultimate-2018-webpack-4-and-babel-setup-guide-npm-yarn-dependencies-compared-entry-points-866b577da6a)? Make sure it also transpiles dependencies (i.e the `vanilla-picker` module).

**Comment by Sphinxxxx** [comment]
Any luck?

**Comment by Sphinxxxx** [comment]
Please update to v2.9.2. The module is now transpiled before release (which I've learnt is the best practice).
